spring.application.name=CONFIG-SERVER

server.port=8888

# Config Repository
spring.cloud.config.server.git.uri=file:///C:/Users/swath/Downloads/day1-microservices
spring.cloud.config.server.git.search-paths=config-repo

# Eureka Configuration
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true